# Generated by Django 4.0.3 on 2022-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_creativity_prorating_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorating',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
