# Generated by Django 4.0.3 on 2022-03-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_prorating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
    ]
